name: Publish Package to npmjs
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4
      - name: Node Setup 🔔
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build 🔨
        run: | 
          yarn
          yarn build
      - name: Publish 🚀
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  storybook-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🔔
        uses: actions/checkout@v4
      - name: Node Setup 🔔
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Install & Build 🔨
        run: |
          yarn
          yarn build:storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          folder: storybook-static